  remote_theme: daviddarnes/alembic

  navigation_header:
    Home: /
    Project 1: /project1/project1.html
    Project 2: /project2/kuykendall_project2.html
    Project 3: /project3/project3.html
    Project 4: /project4/project4.html
